using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Security.DeveloperAuthEndpointFilter")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Hubs.SimulationHub")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.CreateUserRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.CreateAccountRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.CreateProfileRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.SessionCreateRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.SessionJoinRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.LeaderboardSubmission")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.DeveloperPropertyUpdateRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.DeveloperCommandRequest")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated via ASP.NET Core hosting, DI, or minimal API binding.", Scope = "type", Target = "~T:Engine.Server.Models.DeveloperProfileUpsertRequest")]
